#!/bin/sh

# FONT AWESOME 4.7.0

internet(){
    ping -W 1 -c 1 8.8.8.8 >/dev/null 2>&1 # google's dns
}

if ! internet
then
    # echo  # frown
    echo "<span color='yellow'></span>" # exclamation-triangle
    # echo  # hollow
    # echo  # spinner
    # echo  # exclamation-triangle
    exit
fi

# echo  # smile
echo "<span color='#89CFF0'></span>" # circle
